# スクリプト設置場所を作成
- name: "create file {{ ssh_mail_send_trust_list_file }}"
  template:
    src: "ip_trust_list"
    dest: "{{ ssh_mail_send_trust_list_file }}"
    owner: root
    group: root
    mode: 0644
  tags: notification

# 標準出力をSlackに通知するシェルを配置する
- name: "{{ script_dir }}/stdout_to_slack.sh set"
  template:
    src: "stdout_to_slack.sh"
    dest: "{{ script_dir }}/stdout_to_slack.sh"
    owner: root
    group: root
    mode: 0755
  tags: notification

- include: CentOS.yml
  when: "ansible_os_family == 'RedHat'"
  tags: notification

- include: Ubuntu.yml
  when: "ansible_os_family == 'Debian'"
  tags: notification
